import { motion } from "framer-motion";
import { ShieldCheck } from "lucide-react";

import RoleHeader from "../../layout/RoleHeader.jsx";
import Footer from "../../layout/Footer.jsx";

const LAST_UPDATED = "August 10, 2026";
const ENTITY_NAME = "Rocket Trade Pte. Ltd."; // TODO: replace with your registered entity name once incorporated
const CONTACT_EMAIL = "kimanh.work26@gmail.com";

const SECTIONS = [
  {
    title: "1. About This Policy",
    body: [
      ENTITY_NAME + " (\"we\", \"us\", \"the Platform\") is committed to protecting your personal data in accordance with the Personal Data Protection Act 2012 of Singapore (\"PDPA\"). This Privacy Policy explains what personal data we collect, why we collect it, how we use, store, and protect it, and the rights you have over it.",
      "This Policy applies to all users of the Rocket Trade paper trading and market-education platform. By using the Platform, you consent to the collection, use, and disclosure of your personal data as described in this Policy, to the extent permitted by the PDPA.",
    ],
  },
  {
    title: "2. Account & Profile Data",
    body: [
      "When you register, we collect your email address and password, and optionally your full name, username, phone number, and address if you choose to provide them. Your password is never stored in plain text.",
      "If you use the simulated cash portal ('cash in' / 'cash out') feature, we collect a bank name and account number for demonstration purposes only — account numbers are masked (only the last 4 digits are retained) before storage, and no real bank transfer ever takes place. See our Terms of Service for details on which features are simulated.",
    ],
  },
  {
    title: "3. Activity Data",
    body: [
      "We collect data generated by your use of the Platform, including your simulated trading activity (buy/sell orders, holdings, watchlists, price alerts), forum posts, reviews and ratings you leave, expert applications and portfolios you create, gifts sent within the Platform, and your conversations with the AI chatbot.",
      "We also collect standard technical and log data, such as login timestamps and session identifiers, used to keep your account secure and the Platform running smoothly.",
    ],
  },
  {
    title: "4. Subscriptions & Payment Data",
    body: [
      "If you subscribe to a premium plan, your payment is processed by our third-party payment processor, Stripe. We receive confirmation of your subscription status, plan, and billing history, but we do not receive or store your full card number, expiry date, or CVV on our servers — these are handled directly by Stripe in accordance with its own privacy policy and applicable card-industry security standards.",
    ],
  },
  {
    title: "5. Purposes of Use",
    body: [
      "Under the PDPA, we only collect, use, or disclose your personal data where you have given consent, or where collection without consent is permitted or required by law. By registering an account, you consent to our collection and use of your personal data for the purposes below:",
      "To create and manage your account, authenticate you when you log in, and remember your session.",
      "To operate core features of the Platform, including simulated trading, watchlists, alerts, the community forum, expert portfolios, reviews, gifts, and the AI chatbot.",
      "To process premium subscription payments through Stripe and manage billing.",
      "To send account-related notifications by email (such as alerts you set up, forum activity, password resets, or subscription renewal reminders) and to respond to support requests submitted through the Help Centre.",
      "To maintain the security, integrity, and reliability of the Platform, including detecting misuse of the service, and to comply with our legal and regulatory obligations.",
      "We will not use your personal data for a new purpose not disclosed here without first obtaining your consent, unless permitted or required by law.",
    ],
  },
  {
    title: "6. Withdrawing Consent",
    body: [
      "You may withdraw your consent to our collection, use, or disclosure of your personal data at any time by contacting us at " + CONTACT_EMAIL + ", subject to legal or contractual restrictions. Please note that withdrawing consent for certain purposes (for example, account authentication) may mean we are no longer able to provide you with the Platform or particular features, and we will inform you of the likely consequences before acting on your request.",
    ],
  },
  {
    title: "7. Community Content",
    body: [
      "Content you choose to post publicly on the Platform — such as forum posts, comments, reviews, ratings, and expert profiles — is visible to other users of the Platform and, depending on your account and post settings, may be visible to the public. Please avoid including personal data in public posts that you would not want others to see.",
    ],
  },
  {
    title: "8. How We Protect Your Data",
    body: [
      "Account authentication is handled through Firebase Authentication (Google), and application data is stored in our backend database. In accordance with the PDPA's Protection Obligation, we apply reasonable technical and organisational measures — including access controls, password hashing, and secure credential handling — to protect your personal data against unauthorised access, collection, use, disclosure, copying, modification, or disposal.",
      "No online platform can guarantee absolute security. If you believe your account has been compromised, please change your password immediately and contact our support team.",
      "In the event of a data breach that is likely to result in significant harm to affected individuals, or that affects 500 or more individuals, we will notify the Personal Data Protection Commission (PDPC) and affected individuals as required under the PDPA's mandatory data breach notification obligation.",
    ],
  },
  {
    title: "9. Data Retention",
    body: [
      "We retain personal data only for as long as it is necessary to fulfil the purposes for which it was collected, or as required by law (for example, accounting and tax record-keeping obligations). Where personal data is no longer necessary for any of these purposes, we will cease to retain it, or anonymise it, in accordance with the PDPA's Retention Limitation Obligation.",
    ],
  },
  {
    title: "10. Third-Party Services We Use",
    body: [
      "We rely on a small number of third-party service providers to operate the Platform, and personal data is shared with each of them only to the extent needed for them to perform their function:",
      "Firebase Authentication (Google) — handles account sign-up, login, and session security.",
      "Stripe — processes premium subscription payments; handles your payment card details directly.",
      "Brevo and Gmail (SMTP) — send transactional emails such as OTP codes, password resets, welcome emails, and subscription renewal reminders.",
      "Groq — powers the AI investment chatbot; messages you send to the chatbot are transmitted to Groq's API for processing in order to generate a response.",
      "Market data providers (including Yahoo Finance and Alpaca Markets data feeds) — supply the stock prices, charts, and historical data shown on the Platform. These providers do not receive your personal data; only anonymous requests for market data are made.",
      "Some of these providers may process or store data outside Singapore. Where personal data is transferred overseas, we take steps required under the PDPA's Transfer Limitation Obligation to ensure a standard of protection comparable to that under the PDPA.",
    ],
  },
  {
    title: "11. Other Disclosure of Personal Data",
    body: [
      "Beyond the service providers listed in Section 10, we do not sell your personal data, and we do not share it with third parties for their own marketing purposes.",
      "We may disclose personal data if required to do so by law or a competent authority, or to protect the rights, safety, and security of Rocket Trade and its users.",
    ],
  },
  {
    title: "12. Access & Correction Rights",
    body: [
      "Under the PDPA, you have the right to request access to the personal data we hold about you, and to request correction of any error or omission in that data. You can review and update most of your account details directly from your profile settings, or by submitting a request to our Data Protection Officer at " + CONTACT_EMAIL + ".",
      "We will respond to access and correction requests within a reasonable time. We may charge a reasonable fee for access requests as permitted under the PDPA, and will inform you of any applicable fee in advance.",
      "You can manage or cancel a premium subscription from the Subscription page, and manage optional notification preferences from your account's notification settings.",
    ],
  },
  {
    title: "13. Account & Data Deletion",
    body: [
      "You can request deletion of your account and associated personal data at any time by contacting our support team at " + CONTACT_EMAIL + ". Some information may be retained where necessary for legal, security, or record-keeping purposes, as described in Section 9 above.",
    ],
  },
  {
    title: "14. Cookies & Session Data",
    body: [
      "We use session storage to keep you signed in during a browsing session. We do not use this data for third-party advertising, and Rocket Trade does not display ads on the Platform.",
    ],
  },
  {
    title: "15. Children's Privacy",
    body: [
      "Rocket Trade is not directed at children, and accounts require users to be at least 18 years old, the age of majority in Singapore. We do not knowingly collect personal data from children.",
    ],
  },
  {
    title: "16. Changes to This Policy",
    body: [
      "We may update this Privacy Policy from time to time to reflect changes to the Platform or applicable law. We will update the \"Last updated\" date above when changes are made, and will notify you of material changes where required.",
    ],
  },
  {
    title: "17. Our Data Protection Officer & How to Contact Us",
    body: [
      "In accordance with the PDPA, we have appointed a Data Protection Officer (DPO) responsible for ensuring our compliance with the Act. You may contact our DPO with any questions, feedback, or complaints about how your personal data is handled, or to make an access, correction, or withdrawal-of-consent request, by emailing " + CONTACT_EMAIL + ".",
      "If you are not satisfied with our response, you may lodge a complaint with the Personal Data Protection Commission of Singapore (PDPC) at pdpc.gov.sg.",
    ],
  },
];

function PrivacyPolicyPage() {
  return (
    <motion.div
      className="min-h-screen bg-white"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25 }}
    >
      <RoleHeader />

      <section className="relative w-full overflow-hidden bg-linear-to-br from-slate-950 via-blue-950 to-slate-900 pb-14 pt-36 text-white md:pb-20">
        <div className="mx-auto flex w-full max-w-4xl flex-col items-center px-5 text-center md:px-8">
          <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-400/60 bg-cyan-400/5 px-5 py-2 text-xs font-bold tracking-wider text-cyan-400">
            <ShieldCheck size={14} />
            LEGAL
          </div>
          <h1 className="text-4xl font-bold tracking-tight md:text-6xl">
            Privacy{" "}
            <span className="bg-linear-to-r from-cyan-400 to-blue-400 bg-clip-text text-transparent">
              Policy
            </span>
          </h1>
          <p className="mt-5 max-w-2xl text-sm leading-7 text-slate-300 md:text-base">
            This policy explains what personal data Rocket Trade collects, how we use it, and the rights you have under Singapore's Personal Data Protection Act.
          </p>
          <p className="mt-3 text-xs font-medium tracking-wide text-slate-400">
            Last updated: {LAST_UPDATED} · Compliant with the PDPA (Singapore)
          </p>
        </div>
      </section>

      <main className="mx-auto w-full max-w-4xl px-5 py-14 md:px-8 md:py-20">
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-md md:p-10">
          <p className="mb-8 text-sm leading-7 text-slate-600">
            {ENTITY_NAME} ("we", "us", "the Platform") respects your privacy. This Privacy Policy describes how we collect, use, protect, and disclose personal data when you use our paper trading and market-education platform, in accordance with the Personal Data Protection Act 2012 of Singapore.
          </p>

          <div className="space-y-10">
            {SECTIONS.map((section) => (
              <section key={section.title}>
                <h2 className="mb-3 text-lg font-semibold text-slate-800 md:text-xl">
                  {section.title}
                </h2>
                <div className="space-y-3">
                  {section.body.map((paragraph, i) => (
                    <p key={i} className="text-sm leading-7 text-slate-600 md:text-base">
                      {paragraph}
                    </p>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </div>
      </main>

      <Footer />
    </motion.div>
  );
}

export default PrivacyPolicyPage;
